name: Publish Production Docker Image to GitHub Container Registry
on:
  push:
    branches: [ "prod" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21"
      - name: Create application.yml file
        working-directory: ./
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew -x test build
      - name: 도커 설정
        uses: docker/setup-buildx-action@v2
      - name: GitHub Container Registry 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest \
                    -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
